#!/usr/bin/env python3
"""Fetch the official SDKMAN installer script (https://get.sdkman.io) and patch in
sha256 verification for the two archives it downloads - the main CLI and the native
CLI. Upstream only checks these with `unzip -qt`, which catches transit corruption
but not a tampered/substituted archive.

We patch rather than reimplement the installer: every other part of it - directory
scaffolding, etc/config, var/platform inference, shell profile wiring - stays
byte-identical to what upstream ships, so a future installer change we didn't
anticipate still just works. The only way this script can silently miss a real
upstream change is if that change happens to fall inside the two lines we patch
without altering their exact text, which is why the archives are also re-hashed
against the live release on every run rather than trusting a stale pin.

If upstream restructures either download block (the anchors below don't match
exactly once), this exits non-zero instead of silently skipping the patch or
guessing where to insert it - that failure is the signal that a human needs to
look at what changed upstream and update the anchors here.
"""
import argparse
import hashlib
import re
import sys
import urllib.request
from pathlib import Path

GET_SDKMAN_URL = "https://get.sdkman.io"

MAIN_REPO = "sdkman/sdkman-cli"
NATIVE_REPO = "sdkman/sdkman-cli-native"
NATIVE_ARCH_TRIPLES = {
    "x86_64": "x86_64-unknown-linux-gnu",
    "aarch64": "aarch64-unknown-linux-gnu",
}

NATIVE_VERSION_LINE = re.compile(r'export SDKMAN_NATIVE_VERSION="[^"]+"')
MAIN_DOWNLOAD_LINE = (
    'curl --fail --location --progress-bar '
    '"${SDKMAN_SERVICE}/broker/download/sdkman/install/${SDKMAN_VERSION}/${SDKMAN_PLATFORM}" '
    '> "$sdkman_zip_file"'
)
NATIVE_DOWNLOAD_LINE = (
    'curl --fail --location --progress-bar '
    '"${SDKMAN_SERVICE}/broker/download/native/install/${SDKMAN_NATIVE_VERSION}/${SDKMAN_PLATFORM}" '
    '> "$sdkman_zip_file"'
)


def fetch_text(url: str) -> str:
    with urllib.request.urlopen(url) as resp:
        return resp.read().decode()


def sha256_of_url(url: str) -> str:
    digest = hashlib.sha256()
    with urllib.request.urlopen(url) as resp:
        for chunk in iter(lambda: resp.read(1 << 16), b""):
            digest.update(chunk)
    return digest.hexdigest()


def extract_version(script: str, var_name: str) -> str:
    m = re.search(rf'export {var_name}="([^"]+)"', script)
    if not m:
        print(f"::error::Could not find export {var_name}=\"...\" in the installer script", file=sys.stderr)
        raise SystemExit(1)
    return m.group(1)


def insert_after_unique_match(script: str, pattern: "re.Pattern[str]", insertion: str, description: str) -> str:
    matches = list(pattern.finditer(script))
    if len(matches) != 1:
        print(
            f"::error::Expected exactly one match for {description}, found {len(matches)}. "
            "Upstream installer structure changed - update the anchors in this script.",
            file=sys.stderr,
        )
        raise SystemExit(1)
    end = matches[0].end()
    return script[:end] + insertion + script[end:]


def build_hash_block(main_sha256: str, native_sha256_by_arch: dict) -> str:
    arch_cases = "\n".join(
        f'    {arch}) SDKMAN_NATIVE_SHA256="{sha}" ;;' for arch, sha in native_sha256_by_arch.items()
    )
    return f'''

# --- pinned integrity hashes, added locally; regenerated by scripts/patch_sdkman_installer.py ---
SDKMAN_MAIN_SHA256="{main_sha256}"
case "$(uname -m)" in
{arch_cases}
    *) echo "Unsupported architecture: $(uname -m)" >&2; exit 1 ;;
esac

verify_sha256() {{
    local file="$1" expected="$2" actual
    actual=$(sha256sum "$file" | awk '{{print $1}}')
    if [[ "$actual" != "$expected" ]]; then
        echo ""
        echo "Refusing to install: checksum mismatch for $file"
        echo "  expected: $expected"
        echo "  actual:   $actual"
        exit 1
    fi
}}
# --- end pinned integrity hashes ---'''


def patch(script: str, main_sha256: str, native_sha256_by_arch: dict) -> str:
    script = insert_after_unique_match(
        script, NATIVE_VERSION_LINE, build_hash_block(main_sha256, native_sha256_by_arch), "native-version line"
    )
    script = insert_after_unique_match(
        script,
        re.compile(re.escape(MAIN_DOWNLOAD_LINE)),
        '\nverify_sha256 "$sdkman_zip_file" "$SDKMAN_MAIN_SHA256"',
        "main-CLI download line",
    )
    script = insert_after_unique_match(
        script,
        re.compile(re.escape(NATIVE_DOWNLOAD_LINE)),
        '\nverify_sha256 "$sdkman_zip_file" "$SDKMAN_NATIVE_SHA256"',
        "native-CLI download line",
    )
    return script


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--input-file", type=Path, help="Use this local file instead of fetching https://get.sdkman.io (for offline testing)"
    )
    parser.add_argument("--output-file", type=Path, required=True, help="Where to write the patched script")
    args = parser.parse_args()

    script = args.input_file.read_text() if args.input_file else fetch_text(GET_SDKMAN_URL)

    main_version = extract_version(script, "SDKMAN_VERSION")
    native_version = extract_version(script, "SDKMAN_NATIVE_VERSION")
    print(f"Installer declares SDKMAN_VERSION={main_version}, SDKMAN_NATIVE_VERSION={native_version}")

    main_url = f"https://github.com/{MAIN_REPO}/releases/download/{main_version}/sdkman-cli-{main_version}.zip"
    print(f"Hashing {main_url} ...")
    main_sha256 = sha256_of_url(main_url)

    native_sha256_by_arch = {}
    for arch, triple in NATIVE_ARCH_TRIPLES.items():
        native_url = (
            f"https://github.com/{NATIVE_REPO}/releases/download/"
            f"v{native_version}/sdkman-cli-native-{native_version}-{triple}.zip"
        )
        print(f"Hashing {native_url} ...")
        native_sha256_by_arch[arch] = sha256_of_url(native_url)

    patched = patch(script, main_sha256, native_sha256_by_arch)

    previous = args.output_file.read_text() if args.output_file.exists() else None
    if previous == patched:
        print(f"{args.output_file} already up to date.")
        return 0

    args.output_file.write_text(patched)
    print(f"{args.output_file} written ({'updated' if previous is not None else 'created'}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
